[functions]
  directory = "netlify/functions/"
[[headers]]
  for = "/.netlify/functions/comment/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
